### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by ricardo17coelho** [mitevpi/vuetify-component-lib-template#1]
Hi Friend, thx for this very good project.

I tried to install the lib and import it to anthoder project but i have a error. Can you help me please ?
![image](https://user-images.githubusercontent.com/37732431/77996930-da841300-732e-11ea-9df3-34188cdf5bc2.png)
 install lib like : **yarn add file:/path/to/lib**
I tried the methode: _In-Component Import_
`import HelloWorld from "component-library";`
`export default {
   components : {
        HelloWorld
    }
}`

**Comment by mitevpi** [comment]
Are you trying to install it from a local build or have you pushed a build to npm? I'm not very familiar with yarn, but using npm this is how I install it locally:

1. Run `npm run build` in the root directory of the project.
2. Run `npm pack` in the same directory
3. You should now have a `.tgz` file created in your directory.
4. In your other project (where you want to consume the components), run `npm i PATH_TO_TGZ` (substitue PATH_TO_TGZ with the actual file path of the file from step #3)

**Comment by ricardo17coelho** [comment]
Hi friend,Thank you for your quick answer to my question.
I did exaktly what did you say. 
#
`yarn pack`
then install the `.tgz`
and i can import the components like:
**`import { HelloWorld } from "component-library";`**
#
if i try to import like this method:
`import HelloWorld from "component-library/src/components";`
i get this error:
**Cannot find module component-library/src/components'**
and for this method:
`import HelloWorld from "component-library";`
i get this error:
![image](https://user-images.githubusercontent.com/37732431/78101966-622e5800-73e9-11ea-81e3-c5d0bcbeb9de.png)
#
Thx

**Comment by mitevpi** [comment]
I think I had an error in the documentation, and the build/export pattern. I believe I've corrected it, and got it working. This is how I imported the components after installing from the local packed `.tgz`:

![component-template-2](https://user-images.githubusercontent.com/25568566/78130171-c7cd1500-73e6-11ea-93b2-bd7f24920da8.png)
![component-template-3](https://user-images.githubusercontent.com/25568566/78130176-ca2f6f00-73e6-11ea-9870-7d7934a8abbe.png)

**Comment by ricardo17coelho** [comment]
It works. thx!
